extends:
  - airbnb
  - airbnb/hooks
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended

env:
  es2021: true
  browser: true
  jest: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - simple-import-sort

rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  import/order: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function

overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - airbnb-typescript
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: tsconfig.json
    rules:
      '@typescript-eslint/indent': off

  - files: vite.config.js
    rules:
      import/no-extraneous-dependencies: off
